version: '3.8'
services:
  app:
    container_name: "reservations_app_${NODE_ENV}"
    image: "reservations_app"
    depends_on:
      - db
    environment:
      - NODE_ENV:${NODE_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start:dev"]
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run start:dev
  db:
    container_name: "reservations_db_${NODE_ENV}"
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local