version: '3.8'
services:
  app:
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
    command: npm run start:dev
  db:
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
